# Generated by Django 5.1.4 on 2024-12-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(verbose_name='Модель самолета')),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.TextField(verbose_name='Название аэропорта')),
                ('city', models.TextField(verbose_name='Город')),
                ('timezone', models.TextField(verbose_name='Часовой пояс')),
                ('iata_code', models.CharField(max_length=3, verbose_name='IATA код')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
                'db_table': 'airport',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date_start', models.DateTimeField(verbose_name='Дата начала брони')),
                ('book_date_end', models.DateTimeField(verbose_name='Дата окончания брони')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Полная сумма')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Время вылета')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_codes', to='tickets.airports', verbose_name='Код самолета')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airports', to='tickets.airports', verbose_name='Аэропорт прибытия')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airports', to='tickets.airports', verbose_name='Аэропорт вылета')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'db_table': 'flight',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.CharField(max_length=10, verbose_name='Класс обслуживания')),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.airports', verbose_name='Код самолета')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.CharField(max_length=20, verbose_name='Идентификатор пассажира')),
                ('passenger_name', models.TextField(verbose_name='ФИО пассажира')),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.bookings', verbose_name='Номер бронирования')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket_flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.CharField(max_length=10, verbose_name='Класс обслуживания')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flights', verbose_name='Идентификатор рейса')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets', verbose_name='Номер билета')),
            ],
            options={
                'verbose_name': 'Перелет',
                'verbose_name_plural': 'Перелеты',
                'db_table': 'ticket flight',
            },
        ),
    ]
