# Generated by Django 5.1.4 on 2024-12-19 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flights',
            name='aircraft_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_codes', to='tickets.aircrafts', verbose_name='Код самолета'),
        ),
        migrations.AddField(
            model_name='flights',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airports', to='tickets.airports', verbose_name='Аэропорт прибытия'),
        ),
        migrations.AddField(
            model_name='flights',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airports', to='tickets.airports', verbose_name='Аэропорт вылета'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tickets.flights'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tariff'),
        ),
    ]
